version: '${project.version}'
api-version: 1.19
name: BucketFill
main: dev.fluw.bucketfill.BucketFill
author: Fluw
website: https://fluw.dev/
description: A Bucket Fill Plugin
depend: [Vault]
commands:
  bucket:
    description: base command
    aliases: [bf, fillbucket, bucketfill]